<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check-output</name>
   <tag></tag>
   <elementGuidId>2d2fa0d4-9280-4cc3-b393-68feab995f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;output&quot;]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;output&quot;]/div</value>
      <webElementGuid>0fac51f7-f112-4743-a5bf-219e30b9bf82</webElementGuid>
   </webElementProperties>
</WebElementEntity>
