<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt-h1-judul</name>
   <tag></tag>
   <elementGuidId>daaa6114-d97c-4ef5-86de-5492a68019ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div/div/div/div[2]//h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div/div/div/div[2]//h1</value>
      <webElementGuid>5740cb6b-a73e-4d95-9055-9ae07c15bc70</webElementGuid>
   </webElementProperties>
</WebElementEntity>
